### PR TITLE
Islandora Demo Default Content Model Update

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
**GitHub Issue**: [#896](https://github.com/Islandora-CLAW/CLAW/issues/896)

# What does this Pull Request do?

Adds several fields to the default content model.

# What's new?

- New islandora_object fields:
    - field_alternative_title
    - field_description
    - field_edtf_date
    - field_edtf_date_created
    - field_edtf_date_issued
    - field_extent
    - field_identifier
    - field_linked_agent (uses the new RelationType field from controlled_access_terms and populated with MARC relators; resolves [CLAW/issues/893](https://github.com/Islandora-CLAW/CLAW/issues/893))
    - field_member_of
    - field_resource_type
    - field_rights
    - field_subject
- updated rdf.mapping
- new vocabulary for resource types (partially addresses [CLAW/issues/894](https://github.com/Islandora-CLAW/CLAW/issues/894))
- adds dependencies on controlled_access_terms_default_configuration
- implements hook_rdf_namespaces in islandora_demo.module 

# How should this be tested?

From a fresh and current claw-playbook build:

- enable controlled_access_terms_default_configuration
- Apply the PR
- using features, import the changes to the islandora_demo feature
- Make a new repository object (everything should be there and all the fields working properly).

# Additional Notes:

The JSON-LD still has a few quirks with the new profile:
- the new date fields will be given a string type. (See https://github.com/Islandora-CLAW/CLAW/issues/889)
- linked agents will use the contributor predicate regardless of the drop-down. (Related to https://github.com/Islandora-CLAW/CLAW/issues/889)

# Interested parties
@Islandora-CLAW/committers @dannylamb @rosiel

### CODE REVIEW

**Comment by Natkeeran** [comment]
@seth-shaw-unlv This might be me not understanding how the Features update config process works.  But, after running Import Changes, I still see some differences between Active Site Config and Feature Code Config.  Please see the attachment.

Should the date fields be Date type, rather than plan text?

I have 10 empty rows for Rights.  Even though it should be a plain text field.  Attachment 2.

after_import_config_changes

rights

**Comment by seth-shaw-unlv** [comment]
@Natkeeran not completely sure about Features (I still get confused there sometimes). 

As for the dates, they should be plain-text (as crazy as that sounds). They use my Extended Date Time Format widget and formatter with a plain-text field so we aren't constrained by the Date types' Unix timecode.

**Comment by seth-shaw-unlv** [comment]
@Natkeeran it looks like it doesn't like importing dependency configurations, but that shouldn't impact functionality, since they will already be enabled.

**Comment by seth-shaw-unlv** [comment]
Summary from IRC yesterday: 

We want to leave the dates as plain-text/EDTF, in part because it allows importing whatever date strings an institution may have in their data. (I would recommend cleaning them up before import, but that may be just me.) 

Relatedly, by default, the view settings should remain set to plain-text (they are). _The rdf.mapping is configured to use EDTF; should this be changed back to just a string value?_ 

The widget is set to EDTF by default.  I would argue that this is appropriate, because widgets don't impact importing, but they would force objects created or updated via the UI to use a consistent date format standard moving forward (that could be turned off they they really don't want it).

The rights statement cardinality was set to 10 (which made 10 entry rows, most of them unnecessary, in the form view). I've pushed an update that makes it unlimited (only two rows are displayed by default).

Subjects are currently contained in a single subject field. We may break it out into multiple fields to represent Coverage (spatial and temporal) or between People and Corporate Bodies, but that is a question to be deliberated in MIG. In the meantime, we will stick with what we have.

Anything I missed, @Natkeeran and @rosiel?

**Comment by Natkeeran** [comment]
@dannylamb @seth-shaw-unlv I don't seem to have write access to this one.  Please see the notes above.

**Comment by dannylamb** [comment]
@Natkeeran whoops... forgot to add the committer's as a team to this repo when I created it.  You should have the powah now.

**Comment by Natkeeran** [comment]
This PR was briefly discussed at the [MIG Sep 17 meeting](https://github.com/islandora-interest-groups/Islandora-Metadata-Interest-Group/blob/master/Meetings/2018_09_17.md).  It was noted that this is an initial version for review and revision.  It is being merged so that it will be easier for people to review.  MIG contributors and others will review this provide feedback.

**Comment by dannylamb** [comment]
I will rebase my work for Islandora-CLAW/CLAW#888 to include these changes

**Pull request merged**
