### PR TITLE
Solr Search Block

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/953

# What does this Pull Request do?

Adds a solr search block to the second sidebar.

# What's new?
Exported config for the solr search view page and its exposed filters as a block.

# How should this be tested?

- Spin up a new vagrant
- You should not have a search block
- Pull in this PR
- `drush fim -y islandora_demo`
- `drush cr`
- You should have a search block
screenshot from 2019-01-17 14-53-20

# Interested parties
@Natkeeran  @Islandora-CLAW/committers

### CODE REVIEW

**Comment by rosiel** [comment]
Something's wrong with the build, but the feature works.

**Comment by Natkeeran** [comment]
Looks good.  Simpler solution that I thought.  When Travis CI issue resolved, can be merged.

**Comment by whikloj** [comment]
I'm wondering if this is because the `block.block.exposedform  
  solr_search_contentpage_1.yml` is in `config/install` but has a dependency on `views.view.solr_search_content.yml` which is in `config/optional`.

Seems like the required block can't have a dependency on an optional view.

**Comment by dannylamb** [comment]
Yeah, I though that was weird too.  It's just how features exported it.  I can always move it around.

**Comment by whikloj** [comment]
@dannylamb I'd give it a try, just copying the Yaml from `optional` to `install` and see if that solves Travis's problem. Because I assume we will all experience that problem once we try a fresh install with this content.

**Comment by whikloj** [comment]
Whelp that didn't work. I also noticed that the `drupal-scaffold` command has changed to `drupal:scaffold`. I feel like we might have stopped using that, but just incase
https://travis-ci.com/Islandora-CLAW/islandora_demo/jobs/171496440#L741-L747

**Comment by dannylamb** [comment]
Weird...  Ok, I'll dig deeper.

FYI there's an issue for drupal-scaffold: https://github.com/Islandora-CLAW/CLAW/issues/955

**Comment by dannylamb** [comment]
Still the same.  Maybe I just need to add `search_api_solr` to the .info file?

**Comment by Natkeeran** [comment]
@dannylamb Lets try adding `search_api_solr`.  I assume it has dependency to `search_api`.

**Comment by Natkeeran** [comment]
@dannylamb 
I used this https://github.com/Islandora-CLAW/islandora_demo/tree/solr_testing to deploy a new playbook, and it deploys without issues.  Also tried adding `search_api` as dependency, but that did not help, though I assume it has that dependency.   I am out of ideas!

**Comment by Natkeeran** [comment]
@dannylamb 

I understand why travis is failing.

Islandora has dependency to [search_api](https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/islandora.info.yml#L16).  Currently neither islandora or islandora_demo have dependency to search_api_solr.  However, adding that dependency and enabling is not sufficient, because that still does not create [this view](https://github.com/Islandora-CLAW/islandora_demo/pull/15/files#diff-0a03b785a1a94b482c2b4da3a8ab496bR5).  

In ansible, we are doing extra steps to setup the server, and [enable default configs](https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/tasks/drupal.yml#L62).  Specifically, we are enabling search_api_solr_defaults which has the required view.

Thus, if we add **search_api_solr_defaults** as dependency to islandora_demo, travis will pass.

**Comment by Natkeeran** [comment]
yey :+1: :smiley:

**Comment by Natkeeran** [comment]
@dannylamb I'll wait to see if you want to separate this into a sub module.  Otherwise, we can merge it.

**Comment by dannylamb** [comment]
Attempting to submodulize this now.  It makes a block, which depends on carapace, so i'm not making it part of `islandora`, just a submodule to `islandora_demo`.

**Comment by dannylamb** [comment]
Aw crap, ok, it just hit me.  If a submodule has its own composer.json, it's meaningless.  So I'll need to manually `composer require search_api_solr` in the travis file

**Comment by dannylamb** [comment]
@Natkeeran Submodulized and travis is green. :tada:

**Comment by Natkeeran** [comment]
@dannylamb Looks good.  My only suggestion would be to change the name to islandora_search.  

We can add some default facets later on.

**Comment by dannylamb** [comment]
@Natkeeran ...and done.  Now let's see how happy travis is with that.

**Comment by Natkeeran** [comment]
@dannylamb Tested the no search word commit.  Looks good.  Will merge it once travis gives a go.

**Pull request merged**
