### PR TITLE
pdf.js viewer configs

### PR DESCRIPTION
**Pull request by Natkeeran**
# What does this Pull Request do?
This PR adds pdf viewer to islandora_demo.

# What's new?
The steps for creating this viewer are described [here](https://github.com/Natkeeran/Notes/blob/master/configure-new-viewer-in-claw.md).

# How should this be tested?
* Vagrant up
* Install drupal module [pdf](https://www.drupal.org/project/pdf).  Make sure to have the pdf.js library.  (This will be a separate PR).
* Get this PR 
* Run the migration `/admin/structure/migrate/manage/islandora/migrations/islandora_demo_tags` (adds one more display type term)
* Import the changes `/admin/config/development/features/diff/islandora_demo`
* Create a Repository object of binary type, Choose PDFjs for display hint
* Add a media (file), Set Media Use as Original (can be other types as well)
* Ensure that the pdf is displayed using the pdf.js viewer when viewed from the node

# Additional Notes:
* https://github.com/Natkeeran/islandora_pdf/issues/1

# Interested parties
@kayakr @MarcusBarnes  @dannylamb 

@Islandora-CLAW/committers

### CODE REVIEW

**Comment by kayakr** [comment]
In my case:
*  "Get this PR"
   * `cd web/modules/contrib/islandora_demo/`
   *  `wget "https://patch-diff.githubusercontent.com/raw/Islandora-CLAW/islandora_demo/pull/16.patch" -O islandora_demo-16.patch`
   * `patch -p1 <islandora_demo-16.patch`
* "Run the migration"
   * `drush migrate:import islandora_demo_tags`
* "Import the changes"
  * `drush cim -vvv -y --partial --source=modules/contrib/islandora_demo/config/install/`

**Comment by MarcusBarnes** [comment]
@Natkeeran @kayakr I've tested as well.  The PR appears to work as expected.

**Comment by Natkeeran** [comment]
@dannylamb 

Required changes are in.

https://github.com/Islandora-Devops/claw-playbook/pull/90 is probably needs to be merged for Travis to give green.

**Comment by dannylamb** [comment]
@Natkeeran Can you hit the update button?

**Comment by dannylamb** [comment]
thank you kindly @Natkeeran

**Comment by dannylamb** [comment]
Ah, looks like we need to update the travis provisioner script to pull in pdf.js, too https://github.com/Islandora-CLAW/CLAW/blob/master/.scripts/travis_setup_drupal.sh

**Comment by dannylamb** [comment]
@Natkeeran Sorry, got side tracked with Travis and dropped the ball on https://github.com/Islandora-Devops/claw-playbook/pull/90. I went ahead and pulled it in.

I need someone to merge https://github.com/Islandora-CLAW/CLAW/pull/1018 on blind faith who may also be willing to merge a follow up PR if it doesn't work.  I've run the changes on a fresh box pre https://github.com/Islandora-Devops/claw-playbook/pull/90 and it ran fine FWIW.

**Comment by dannylamb** [comment]
Oh noes... timeout issues.  Dangit travis!

**Comment by dannylamb** [comment]
Odd.  I'm getting this about controlled_access_terms

```bash
In DiscoveryTrait.php line 52:
                                                
  The "text_edtf_human" plugin does not exist.  
                                                
```

@seth-shaw-unlv recently renamed `text_edtf_human` to `edtf_default`.  Maybe we missed updating a spot in `islandora_demo`.  I'll check it out.

**Comment by dannylamb** [comment]
Oh, I see now.  They're tangled up in this PR.  @Natkeeran can you make sure you've got the latest `controlld_access_terms`, run `drush updb`, and then re-export the feature?  That  should automatically update all the config to use the new field type.

**Comment by Natkeeran** [comment]
@dannylamb 
Sure.  What I'll do is get the latest claw-playbook, and re export this feature.

**Pull request merged**
