### PR TITLE
Issue 888

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Islandora-CLAW/CLAW#888

# What does this Pull Request do?

Configuration changes for Islandora-CLAW/CLAW#888

# How should this be tested?

https://github.com/Islandora-Devops/claw-playbook/pull/79

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
This PR made me realize we need to enable Travis on this repo.

**Comment by dannylamb** [comment]
@whikloj I'll use this as an excuse to switch to Github's new "apps" instead of "services" for running Travis.

**Comment by whikloj** [comment]
I'm not sure that there is a Github "app" for Travis, as those "apps" generally cost 💵

**Comment by dannylamb** [comment]
@whikloj Yeah, just ran into that.  It tries to sell you a "pro" account for Travis, but if you say it's open source it gives it to you for free.

**Comment by whikloj** [comment]
@dannylamb stay free baby, stay free

**Comment by dannylamb** [comment]
@whikloj Ok, took some finagling, but I've got us all updated to the new app and it is triggering Travis builds on PRs now.

**Comment by dannylamb** [comment]
@whikloj Oooh... looks like some content_browser stuff didn't clean itself out when I disabled it in the form settings.  Let me take care of that.

**Comment by dannylamb** [comment]
:sob: I've got some dependency issues going on.  I'm going to have to revert all over and point back to issue-888 branches to sort this out.

**Comment by dannylamb** [comment]
OK, well it installs at least.  So now just Travis to sort out.

**Comment by dannylamb** [comment]
Alright.... I'm done messing around with these.  I moved the `access_control` vocabulary and field_storage to `islandora_demo` to completely decouple access control strategies from core `islandora`.  This opens things up for folks that want `og` and the like.

One last vagrant up to make sure.  Once Travis is green, these are good to go again.

**Pull request merged**
